global:
  podCIDR: ""
config:
  veth_mtu: 1440
  backend: bird
  monitoring:
    enabled: true
    felixMetricsPort: 9091
    typhaMetricsPort: 9093
  ipam:
    type: "host-local"
    # subnet: "usePodCidr"
  feature_control: 
    floating_ips: false
  kubeControllers:
    enabled: true
  typha:
    enabled: true
  ipv4:
    pool: ipip # or vxlan
    mode: "Always"
    autoDetectionMethod: "first-found"
  felix:
    ipinip:
      enabled: "true"
images:
  calico-node: "image-repository:image-tag"
  calico-cni: "image-repository:image-tag"
  calico-typha: "image-repository:image-tag"
  calico-kube-controllers: "image-repository:image-tag"
  calico-podtodaemon-flex: "image-repository:image-tag"
  calico-cpva: "image-repository:image-tag"
  calico-cpa: "image-repository:image-tag"

vpa:
  enabled: false

# nodeSelector: {}
